In [ ]:
import torch
from torch.autograd import grad

In [7]:
x=torch.tensor([5], dtype=torch.float)
w=torch.tensor([1], requires_grad=True, dtype=torch.float)
b=torch.tensor([1], requires_grad=True,  dtype=torch.float)

In [8]:
def relu(z):
    if z<=0:
        return 0
    else:
        return z

In [34]:
z=torch.matmul(x,w)+b
y=relu(z)
y

tensor([6.], grad_fn=<AddBackward0>)

In [29]:
derv_w=grad(y,w,retain_graph=True)

In [30]:
derv_w

(tensor([5.]),)

In [ ]:
from torch.nn import functional # built in funtion provided by torch

In [33]:
y=functional.relu(z)
y

tensor([6.], grad_fn=<ReluBackward0>)