In [1]:
import torch

In [ ]:
#one hot encoding
def one_hot_encode(y, classes):
    one_hot=torch.zeros(len(y), classes)
    one_hot.scatter_(1,y.view(-1,1),1).float()
    return one_hot

In [13]:
y = torch.tensor([0, 1, 2, 2])
y_enc = one_hot_encode(y, 3)
print(y_enc)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


In [54]:
def softmax(x):
    softm=(torch.exp(x.t())/torch.sum(torch.exp(x), dim=1)).t()
    return softm


x=torch.tensor(
    [[-0.1, -0.5, -0.5],
     [-3, -1.0, -2.6],
     [-2.5, -0.5, -0.3],
     [-2.5, -0.5, -0.1]])
res=softmax(x)

In [58]:
print(res)

tensor([[0.4272, 0.2864, 0.2864],
        [0.1012, 0.7478, 0.1510],
        [0.0574, 0.4243, 0.5183],
        [0.0515, 0.3806, 0.5678]])


In [56]:
z=torch.tensor([0,1,1,2])
torch.argmax(z)

tensor(3)

In [57]:
def cross_entropy(res, y_enc):
    print(torch.log(res) * (y_enc))
    return - torch.sum(torch.log(res) * (y_enc), dim=1)

xent = cross_entropy(res, y_enc)
print('Cross Entropy:', xent)

tensor([[-0.8504, -0.0000, -0.0000],
        [-0.0000, -0.2906, -0.0000],
        [-0.0000, -0.0000, -0.6573],
        [-0.0000, -0.0000, -0.5659]])
Cross Entropy: tensor([0.8504, 0.2906, 0.6573, 0.5659])


In [61]:
# Auto way to calculate in pytorch
from torch.nn import functional

In [64]:
functional.nll_loss(torch.log(res), y, reduction='none')

tensor([0.8504, 0.2906, 0.6573, 0.5659])

In [ ]:
functional.cross_entropy(x, y, reduction='sum')

tensor(2.3642)